# Generated by Django 3.1.4 on 2021-02-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='event',
        ),
        migrations.AlterField(
            model_name='idea',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recipient'),
        ),
    ]
